import React,{useEffect,useState} from 'react';
import {Alert,Image,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';import * as ImagePicker from 'expo-image-picker';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/types';import {blogsService} from '../services/api/blogs.service';import {postsService} from '../services/api/posts.service';import {colors,radii,spacing,typography} from '../theme';
type Props=NativeStackScreenProps<RootStackParamList,'ArticleEditor'>;
export default function ArticleEditorScreen({route,navigation}:Props){const {blogId,articleId}=route.params;const [title,setTitle]=useState('');const [body,setBody]=useState('');const [cover,setCover]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{if(!articleId)return;blogsService.articles(blogId).then(rows=>{const a=rows.find(x=>x.id===articleId);if(a){setTitle(a.title);setBody(a.body||'');setCover(a.cover||'')}})},[articleId,blogId]);const image=async()=>{const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8});if(!picked.canceled){setBusy(true);try{setCover(await postsService.uploadImage(picked.assets[0].uri))}catch(e){Alert.alert('Upload failed',(e as Error).message)}finally{setBusy(false)}}};const save=async(status:string)=>{if(!title.trim())return Alert.alert('Title required');setBusy(true);try{const value={blogId,title:title.trim(),body:body.trim(),cover:cover||undefined,status};if(articleId)await blogsService.updateArticle(articleId,value);else await blogsService.createArticle(value);Alert.alert('Saved',status==='published'?'Article published.':'Draft saved.',[{text:'Done',onPress:()=>navigation.goBack()}]);}catch(e){Alert.alert('Unable to save',(e as Error).message)}finally{setBusy(false)}};return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="close" size={24}/></TouchableOpacity><Text style={s.heading}>{articleId?'Edit Article':'New Article'}</Text><TouchableOpacity disabled={busy} onPress={()=>save('draft')}><Text style={s.link}>Draft</Text></TouchableOpacity></View><View style={s.content}><TextInput style={s.title} value={title} onChangeText={setTitle} placeholder="Article title"/>{cover?<Image source={{uri:cover}} style={s.image}/>:null}<TouchableOpacity style={s.upload} onPress={image}><Ionicons name="image-outline" size={20} color={colors.primary}/><Text style={s.link}>Upload cover image</Text></TouchableOpacity><TextInput style={s.body} value={body} onChangeText={setBody} placeholder="Write your article…" multiline textAlignVertical="top"/><TouchableOpacity style={s.publish} disabled={busy} onPress={()=>save('published')}><Text style={s.publishText}>{busy?'Saving…':'Publish'}</Text></TouchableOpacity></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:spacing.lg},heading:{...typography.h2},link:{color:colors.primary,fontWeight:'700'},content:{padding:spacing.lg,gap:spacing.md,flex:1},title:{backgroundColor:colors.card,borderRadius:radii.lg,padding:spacing.md,fontSize:20,fontWeight:'700'},body:{backgroundColor:colors.card,borderRadius:radii.lg,padding:spacing.md,minHeight:240,flex:1},upload:{flexDirection:'row',gap:8,alignItems:'center'},image:{width:'100%',height:160,borderRadius:radii.lg},publish:{backgroundColor:colors.primary,borderRadius:radii.pill,padding:spacing.md,alignItems:'center'},publishText:{color:colors.white,fontWeight:'700'}});
