import React,{useEffect,useRef,useState} from 'react';
import {Alert,FlatList,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/types';
import {socialService,type DirectMessage} from '../services/api/social.service';
import {useAuth} from '../context/AuthContext';
import Avatar from '../components/Avatar';
import {colors,radii,spacing} from '../theme';

type Props=NativeStackScreenProps<RootStackParamList,'DirectMessage'>;
export default function DirectMessageScreen({route,navigation}:Props){const {userId,name,avatar}=route.params;const {user}=useAuth();const [messages,setMessages]=useState<DirectMessage[]>([]);const [text,setText]=useState('');const [loading,setLoading]=useState(true);const list=useRef<FlatList<DirectMessage>>(null);const load=async()=>{try{setMessages(await socialService.getMessages(userId));}catch(e){Alert.alert('Unable to load messages',(e as Error).message);}finally{setLoading(false);}};useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer);},[userId]);const send=async()=>{if(!text.trim())return;const value=text.trim();setText('');try{const message=await socialService.sendMessage(userId,value);setMessages(current=>[...current,message]);}catch(e){setText(value);Alert.alert('Unable to send',(e as Error).message);}};return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={24}/></TouchableOpacity><Avatar uri={avatar||''} size={38}/><Text style={s.name}>{name}</Text></View><FlatList ref={list} data={messages} keyExtractor={x=>x.id} contentContainerStyle={s.list} onContentSizeChange={()=>list.current?.scrollToEnd({animated:true})} ListEmptyComponent={<Text style={s.empty}>{loading?'Loading messages…':'No messages yet. Say hello.'}</Text>} renderItem={({item})=>{const mine=item.senderId===user?.id;return <View style={[s.bubble,mine?s.mine:s.theirs]}><Text style={[s.message,mine&&s.mineText]}>{item.text}</Text><Text style={[s.time,mine&&s.mineTime]}>{new Date(item.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</Text></View>}}/><View style={s.composer}><TextInput style={s.input} value={text} onChangeText={setText} placeholder="Message…" multiline/><TouchableOpacity style={s.send} onPress={send}><Ionicons name="send" size={18} color={colors.white}/></TouchableOpacity></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',gap:spacing.sm,padding:spacing.md,borderBottomWidth:1,borderBottomColor:colors.border},name:{fontSize:16,fontWeight:'800',color:colors.textPrimary},list:{padding:spacing.lg,gap:spacing.sm},empty:{textAlign:'center',color:colors.textMuted,marginTop:spacing.xxl},bubble:{maxWidth:'80%',paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radii.xl},mine:{alignSelf:'flex-end',backgroundColor:colors.primary},theirs:{alignSelf:'flex-start',backgroundColor:colors.card},message:{color:colors.textPrimary},mineText:{color:colors.white},time:{fontSize:9,color:colors.textMuted,marginTop:3},mineTime:{color:'rgba(255,255,255,.7)'},composer:{flexDirection:'row',alignItems:'flex-end',gap:spacing.sm,padding:spacing.md,borderTopWidth:1,borderTopColor:colors.border},input:{flex:1,maxHeight:100,backgroundColor:colors.card,borderRadius:radii.xl,paddingHorizontal:spacing.md,paddingVertical:10,color:colors.textPrimary},send:{width:42,height:42,borderRadius:21,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'}});
