import React,{useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {mealsService} from '../services/api/meals.service';
import type {RootStackParamList} from '../navigation/types';
import {colors,radii,spacing,typography} from '../theme';
type Props=NativeStackScreenProps<RootStackParamList,'MealEditor'>;
export default function MealEditorScreen({route,navigation}:Props){const p=route.params;const initial=p.meal;const [name,setName]=useState(initial?.name||'');const [mealType,setMealType]=useState(initial?.mealType||'Breakfast');const [kcal,setKcal]=useState(initial?.kcal?.toString()||'');const [protein,setProtein]=useState(initial?.protein?.toString()||'');const [carbs,setCarbs]=useState(initial?.carbs?.toString()||'');const [fats,setFats]=useState(initial?.fats?.toString()||'');const [busy,setBusy]=useState(false);
const save=async()=>{if(!name.trim()||Number(kcal)<=0)return Alert.alert('Missing details','Enter a meal name and calories.');const payload={name:name.trim(),mealType,kcal:Number(kcal),protein:Number(protein)||0,carbs:Number(carbs)||0,fats:Number(fats)||0,ts:new Date(`${p.date}T12:00:00`).getTime()};try{setBusy(true);if(initial?.id)await mealsService.update(initial.id,payload);else await mealsService.log(payload);navigation.goBack();}catch(e){Alert.alert('Unable to save meal',(e as Error).message);}finally{setBusy(false);}};
return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="close" size={24}/></TouchableOpacity><Text style={s.title}>{initial?'Edit Meal':'Add Meal'}</Text><View style={{width:24}}/></View><ScrollView contentContainerStyle={s.content}><Text style={s.label}>Meal name</Text><TextInput style={s.input} value={name} onChangeText={setName}/><Text style={s.label}>Meal type</Text><View style={s.types}>{['Breakfast','Lunch','Dinner','Snack'].map(x=><TouchableOpacity key={x} style={[s.type,mealType===x&&s.active]} onPress={()=>setMealType(x)}><Text style={mealType===x?s.activeText:s.typeText}>{x}</Text></TouchableOpacity>)}</View><Text style={s.label}>Calories</Text><TextInput style={s.input} value={kcal} onChangeText={setKcal} keyboardType="decimal-pad"/><View style={s.columns}>{[['Protein',protein,setProtein],['Carbs',carbs,setCarbs],['Fat',fats,setFats]].map(([l,v,f])=><View style={{flex:1}} key={l as string}><Text style={s.label}>{l as string} (g)</Text><TextInput style={s.input} value={v as string} onChangeText={f as (x:string)=>void} keyboardType="decimal-pad"/></View>)}</View><TouchableOpacity style={s.button} onPress={save} disabled={busy}><Text style={s.buttonText}>{busy?'Saving…':'Save Meal'}</Text></TouchableOpacity></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:spacing.lg},title:{...typography.h2},content:{padding:spacing.lg},label:{...typography.caption,color:colors.textSecondary,marginTop:spacing.md,marginBottom:spacing.sm},input:{backgroundColor:colors.card,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,padding:spacing.md},types:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},type:{borderWidth:1,borderColor:colors.border,borderRadius:radii.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},active:{backgroundColor:colors.primary,borderColor:colors.primary},typeText:{color:colors.textSecondary},activeText:{color:colors.white,fontWeight:'700'},columns:{flexDirection:'row',gap:spacing.sm},button:{backgroundColor:colors.primary,borderRadius:radii.pill,padding:spacing.md,alignItems:'center',marginTop:spacing.xl},buttonText:{color:colors.white,fontWeight:'700'}});
