import React,{useEffect,useState} from 'react';
import {Alert,Image,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/types';
import {earnService,type EarnAsset,type MembershipMetadata} from '../services/api/earn.service';
import {colors,radii,spacing} from '../theme';
type Props=NativeStackScreenProps<RootStackParamList,'MembershipPublic'>;
export default function MembershipPublicScreen({route,navigation}:Props){const [a,setA]=useState<EarnAsset|null>(null);useEffect(()=>{earnService.getAsset(route.params.membershipId).then(setA).catch(e=>Alert.alert('Unable to load',e.message))},[route.params.membershipId]);if(!a)return <SafeAreaView style={s.safe}><Text style={s.load}>Loading membership…</Text></SafeAreaView>;const md=a.metadata as MembershipMetadata||{};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><TouchableOpacity style={s.back} onPress={navigation.goBack}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><Image source={{uri:md.banner||`https://picsum.photos/seed/banner-${a.id}/800/350`}} style={s.banner}/><Image source={{uri:md.profileImage||`https://picsum.photos/seed/${a.id}/200`}} style={s.avatar}/><Text style={s.title}>{a.title}</Text><Text style={s.creator}>A Zero community · {Number(a.metrics?.members||0)} members</Text><Text style={s.desc}>{a.description}</Text><Text style={s.section}>What members receive</Text><Text style={s.desc}>{md.memberReceives||md.valueProposition}</Text><View style={s.benefits}>{md.benefits?.map(x=><View key={x} style={s.benefit}><Ionicons name="checkmark-circle" size={17} color={colors.success}/><Text style={s.benefitText}>{x}</Text></View>)}</View><Text style={s.section}>Membership options</Text>{md.tiers?.map(t=><View key={t.id} style={[s.tier,{borderColor:t.color}]}><Text style={s.tierName}>{t.name}</Text><Text style={s.desc}>{t.description}</Text><Text style={s.price}>${t.monthly||0}/month · ${t.annual||0}/year</Text><Text style={s.trial}>{t.trial||md.trial}</Text><TouchableOpacity style={s.join} onPress={()=>navigation.navigate('MembershipCheckout',{membershipId:a.id,tierId:t.id})}><Text style={s.joinText}>{String(t.trial||md.trial).includes('No free')?'Join':'Start Free Trial'}</Text></TouchableOpacity></View>)}{!md.tiers?.length&&<TouchableOpacity style={s.join} onPress={()=>navigation.navigate('MembershipCheckout',{membershipId:a.id})}><Text style={s.joinText}>{String(md.trial).includes('No free')?'Join Community':'Start Free Trial'}</Text></TouchableOpacity>}<Text style={s.section}>Frequently asked questions</Text>{md.faqs?.map((x,i)=><View key={i} style={s.faq}><Text style={s.faqQ}>{x.question}</Text><Text style={s.desc}>{x.answer}</Text></View>)}<Text style={s.section}>Community rules</Text><Text style={s.desc}>{md.rules}</Text><Text style={s.section}>Reviews and testimonials</Text>{md.testimonials?.map((x,i)=><Text key={i} style={s.quote}>“{x}”</Text>)}<TouchableOpacity><Text style={s.signIn}>Already a member? Sign in</Text></TouchableOpacity></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},load:{textAlign:'center',marginTop:100},content:{paddingBottom:40},back:{position:'absolute',zIndex:2,top:10,left:12,backgroundColor:'rgba(255,255,255,.85)',padding:7,borderRadius:20},banner:{width:'100%',height:180},avatar:{width:85,height:85,borderRadius:22,marginTop:-42,marginLeft:18,borderWidth:4,borderColor:'#fff'},title:{fontSize:23,fontWeight:'900',marginHorizontal:18,marginTop:10},creator:{fontSize:11,color:colors.textSecondary,marginHorizontal:18,marginTop:4},desc:{fontSize:12,color:colors.textSecondary,lineHeight:18,marginTop:7},section:{fontSize:16,fontWeight:'900',marginHorizontal:18,marginTop:22,marginBottom:6},benefits:{marginHorizontal:18},benefit:{flexDirection:'row',gap:8,alignItems:'center',marginTop:8},benefitText:{fontSize:12},tier:{backgroundColor:'#fff',borderWidth:2,borderRadius:radii.xl,padding:16,marginHorizontal:18,marginBottom:10},tierName:{fontSize:16,fontWeight:'900'},price:{fontSize:17,fontWeight:'900',color:colors.primary,marginTop:10},trial:{fontSize:10.5,color:colors.success,fontWeight:'700',marginTop:4},join:{backgroundColor:colors.primary,borderRadius:radii.pill,padding:13,alignItems:'center',marginTop:12,marginHorizontal:18},joinText:{color:'#fff',fontWeight:'900'},faq:{backgroundColor:'#fff',borderRadius:radii.lg,padding:13,marginHorizontal:18,marginTop:8},faqQ:{fontSize:12.5,fontWeight:'800'},quote:{backgroundColor:'#fff',borderRadius:radii.lg,padding:13,marginHorizontal:18,marginTop:8,fontSize:12,fontStyle:'italic'},signIn:{textAlign:'center',color:colors.primary,fontWeight:'800',marginTop:25}});
