import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/types';
import {earnService,type EarnAsset,type MembershipMetadata} from '../services/api/earn.service';
import {colors,radii} from '../theme';
type Props=NativeStackScreenProps<RootStackParamList,'MembershipCheckout'>;
export default function MembershipCheckoutScreen({route,navigation}:Props){const [a,setA]=useState<EarnAsset|null>(null);const [interval,setIntervalValue]=useState<'monthly'|'quarterly'|'sixMonth'|'annual'|'lifetime'>('monthly');useEffect(()=>{earnService.getAsset(route.params.membershipId).then(setA).catch(e=>Alert.alert('Unable to load',e.message))},[route.params.membershipId]);if(!a)return <SafeAreaView style={s.safe}/>;const md=a.metadata as MembershipMetadata||{},tier=md.tiers?.find(x=>x.id===route.params.tierId);const price=Number(tier?.[interval]??({monthly:md.monthlyPrice,quarterly:md.quarterlyPrice,sixMonth:md.sixMonthPrice,annual:md.annualPrice,lifetime:md.lifetimePrice}[interval])??0);const trial=tier?.trial||md.trial||'No free trial';const dueToday=trial==='No free trial'?price:0;const days=Number(trial.match(/\d+/)?.[0]||0);const next=new Date(Date.now()+days*86400000).toLocaleDateString();return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={navigation.goBack}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><Text style={s.headerTitle}>Membership checkout</Text><View style={{width:23}}/></View><ScrollView contentContainerStyle={s.content}><Text style={s.community}>{a.title}</Text><Text style={s.tier}>{tier?.name||'Community membership'}</Text><Text style={s.label}>Billing frequency</Text><View style={s.options}>{(['monthly','quarterly','sixMonth','annual','lifetime'] as const).map(x=><TouchableOpacity key={x} style={[s.option,x===interval&&s.optionOn]} onPress={()=>setIntervalValue(x)}><Text style={[s.optionText,x===interval&&s.optionTextOn]}>{x}</Text></TouchableOpacity>)}</View><View style={s.summary}><Line label="Trial length" value={trial}/><Line label="Amount due today" value={`${md.currency||'USD'} ${dueToday.toFixed(2)}`}/><Line label="Amount after trial" value={`${md.currency||'USD'} ${price.toFixed(2)}`}/><Line label="Billing interval" value={interval}/><Line label="Next billing date" value={trial==='No free trial'?'Today':next}/><Line label="Automatic renewal" value={md.autoRenew?'Enabled':'Disabled'}/><Line label="Trial reminder" value={md.trialReminder?'Before trial ends':'No reminder'}/></View><Text style={s.terms}>{md.lifetimeTerms||'Cancel before renewal to avoid the next charge. Access continues through the paid billing period.'}</Text><TouchableOpacity style={s.payment}><Ionicons name="card-outline" size={20}/><Text style={s.paymentText}>Payment method</Text><Text style={s.change}>Add or change</Text></TouchableOpacity><TouchableOpacity style={s.confirm} onPress={()=>Alert.alert('Membership confirmed','The payment provider will confirm access and add you to the connected Zero community.')}><Text style={s.confirmText}>Confirm Membership</Text></TouchableOpacity></ScrollView></SafeAreaView>}
function Line({label,value}:{label:string;value:string}){return <View style={s.line}><Text style={s.lineLabel}>{label}</Text><Text style={s.lineValue}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16},headerTitle:{fontSize:16,fontWeight:'900'},content:{padding:18},community:{fontSize:21,fontWeight:'900'},tier:{fontSize:13,color:colors.primary,fontWeight:'800',marginTop:4},label:{fontSize:11,fontWeight:'800',marginTop:22,marginBottom:8},options:{flexDirection:'row',flexWrap:'wrap',gap:7},option:{borderWidth:1,borderColor:colors.border,borderRadius:radii.pill,paddingHorizontal:11,paddingVertical:8},optionOn:{backgroundColor:colors.primary,borderColor:colors.primary},optionText:{fontSize:10.5},optionTextOn:{color:'#fff',fontWeight:'800'},summary:{backgroundColor:'#fff',borderRadius:radii.xl,padding:15,marginTop:18},line:{flexDirection:'row',justifyContent:'space-between',paddingVertical:10,borderBottomWidth:1,borderColor:colors.border,gap:12},lineLabel:{fontSize:11,color:colors.textSecondary},lineValue:{fontSize:11,fontWeight:'800',textAlign:'right'},terms:{fontSize:10.5,color:colors.textSecondary,lineHeight:16,marginTop:13},payment:{backgroundColor:'#fff',borderRadius:radii.lg,padding:15,flexDirection:'row',alignItems:'center',gap:10,marginTop:16},paymentText:{flex:1,fontWeight:'700'},change:{color:colors.primary,fontWeight:'800',fontSize:11},confirm:{backgroundColor:colors.primary,borderRadius:radii.pill,padding:15,alignItems:'center',marginTop:18},confirmText:{color:'#fff',fontWeight:'900'}});
