import React, { useCallback, useState } from 'react';
import { Alert, Image, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/types';
import { earnService, type EarnAsset, type PdfMetadata } from '../services/api/earn.service';
import StatusBadge from './earn/components/StatusBadge';
import { colors, radii, shadow, spacing, typography } from '../theme';

type Props=NativeStackScreenProps<RootStackParamList,'PdfDashboard'>;
const ACTIONS=[['Edit details','create-outline','edit'],['Replace PDF','swap-horizontal-outline','edit'],['Upload new edition','cloud-upload-outline','edit'],['Change cover','image-outline','edit'],['Preview settings','eye-outline','edit'],['Pricing & discounts','pricetag-outline','edit'],['View public page','globe-outline','reader'],['Copy/share PDF link','link-outline','share'],['Generate QR code','qr-code-outline','qr'],['Promote with Audience Engine','megaphone-outline','promote'],['Add to membership','people-outline','membership'],['Add to bundle','albums-outline','bundle'],['Unpublish / pause','pause-circle-outline','pause'],['Archive PDF','archive-outline','archive'],['Delete PDF','trash-outline','delete']] as const;
export default function PdfDashboardScreen({route,navigation}:Props){
 const [pdf,setPdf]=useState<EarnAsset|null>(null);const [error,setError]=useState('');
 const load=useCallback(()=>earnService.getAsset(route.params.pdfId).then(setPdf).catch(e=>setError(e.message)),[route.params.pdfId]);
 useFocusEffect(useCallback(()=>{load();},[load]));
 if(!pdf)return <SafeAreaView style={s.safe}><Header title="PDF dashboard" back={navigation.goBack}/><Text style={s.empty}>{error||'Loading PDF…'}</Text></SafeAreaView>;
 const m=pdf.metrics||{}, md=pdf.metadata as PdfMetadata||{};const views=Number(m.views||0),purchases=Number(m.purchases||0);const conversion=views?purchases/views*100:0;
 const act=async(key:string)=>{if(key==='edit')return navigation.navigate('PdfEditor',{pdfId:pdf.id,mode:pdf.subtype});if(key==='reader')return navigation.navigate('PdfReader',{pdfId:pdf.id,preview:true});if(key==='promote')return navigation.navigate('AudienceEngine',{sourceLabel:pdf.title,pdfId:pdf.id});if(key==='share')return Share.share({message:`Preview ${pdf.title}: teamcal://pdf/${pdf.id}`});if(key==='qr')return Alert.alert('QR link',`teamcal://pdf/${pdf.id}`);if(key==='pause'||key==='archive'){const updated=await earnService.updateAsset(pdf.id,{status:key==='archive'?'archived':pdf.status==='paused'?'published':'paused'});setPdf(updated);return;}if(key==='delete')return Alert.alert('Delete PDF?','This permanently removes the PDF listing.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>earnService.deleteAsset(pdf.id).then(()=>navigation.goBack())}]);Alert.alert('Saved',key==='membership'?'PDF can now be selected by your memberships.':'PDF can now be selected in product bundles.');};
 return <SafeAreaView style={s.safe} edges={['top']}><Header title={pdf.title} back={navigation.goBack}/><ScrollView contentContainerStyle={s.content}><View style={[s.hero,shadow.card]}><Image source={{uri:pdf.image||`https://picsum.photos/seed/${pdf.id}/320/460`}} style={s.cover}/><View style={{flex:1}}><View style={s.titleRow}><Text style={s.title}>{pdf.title}</Text><StatusBadge status={pdf.status}/></View><Text style={s.author}>{md.author||'Independent creator'} · {md.category||'Digital resource'}</Text><Text style={s.price}>{pdf.metadata?.pricingModel==='free'?'Free':`${pdf.currency} ${Number(pdf.price).toFixed(2)}`}</Text><TouchableOpacity style={s.preview} onPress={()=>navigation.navigate('PdfReader',{pdfId:pdf.id,preview:true})}><Text style={s.previewText}>Open preview</Text></TouchableOpacity></View></View>
 <Text style={s.sectionTitle}>Performance summary</Text><View style={s.grid}><Stat label="Preview views" value={views}/><Stat label="Full purchases" value={purchases}/><Stat label="Readers" value={Number(m.readers||purchases)}/><Stat label="Completion" value={`${Number(m.completion||0).toFixed(1)}%`}/><Stat label="Downloads" value={Number(m.downloads||0)}/><Stat label="Reviews" value={(md.reviews||[]).length}/><Stat label="Rating" value={`${Number(m.rating||0).toFixed(1)} ★`}/><Stat label="Refunds" value={Number(m.refunds||0)}/><Stat label="Total earnings" value={`$${Number(m.earned||0).toFixed(2)}`}/><Stat label="Conversion" value={`${conversion.toFixed(1)}%`}/></View>
 <Text style={s.sectionTitle}>Sales funnel</Text><View style={[s.card,shadow.soft]}>{[['Page opened',m.pageViews||views],['Preview started',m.previewStarts||views],['Preview completed',m.previewCompleted||0],['Buy clicked',m.buyClicks||0],['Payment completed',purchases]].map(([x,v],i)=><View key={String(x)} style={s.funnel}><Text style={s.funnelLabel}>{x}</Text><View style={[s.bar,{width:`${Math.max(3,100-i*18)}%`}]} /><Text style={s.funnelValue}>{Number(v)}</Text></View>)}</View>
 <Text style={s.sectionTitle}>Audience insights</Text><View style={[s.card,shadow.soft]}><Text style={s.insight}>Top locations and traffic sources will appear as readers discover this PDF.</Text><View style={s.insightRow}><Stat label="Top country" value={String(m.topCountry||'—')}/><Stat label="Top source" value={String(m.topSource||'—')}/></View><Text style={s.insight}>Most-read pages: {String(m.mostReadPages||'Not enough data')}</Text></View>
 <Text style={s.sectionTitle}>Reviews and ratings</Text><TouchableOpacity style={[s.card,shadow.soft]} onPress={()=>navigation.navigate('PdfReviews',{pdfId:pdf.id})}><Text style={s.actionLabel}>{(md.reviews||[]).length} reviews · View, reply and moderate</Text><Ionicons name="chevron-forward" size={18}/></TouchableOpacity>
 <Text style={s.sectionTitle}>PDF settings and actions</Text><View style={[s.card,shadow.soft]}>{ACTIONS.map(([label,icon,key],i)=><TouchableOpacity key={label} style={[s.action,i===ACTIONS.length-1&&{borderBottomWidth:0}]} onPress={()=>act(key)}><Ionicons name={icon} size={18} color={key==='delete'?'#D33':colors.primary}/><Text style={[s.actionLabel,key==='delete'&&{color:'#D33'}]}>{label}</Text><Ionicons name="chevron-forward" size={16} color={colors.textMuted}/></TouchableOpacity>)}</View></ScrollView></SafeAreaView>
}
function Header({title,back}:{title:string;back:()=>void}){return <View style={s.header}><TouchableOpacity onPress={back}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><Text style={s.headerTitle} numberOfLines={1}>{title}</Text><View style={{width:23}}/></View>}
function Stat({label,value}:{label:string;value:string|number}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.lg},headerTitle:{...typography.h2,flex:1,textAlign:'center'},content:{padding:spacing.lg,paddingBottom:40},empty:{textAlign:'center',marginTop:80,color:colors.textSecondary},hero:{backgroundColor:colors.card,borderRadius:radii.xl,padding:spacing.md,flexDirection:'row',gap:spacing.md},cover:{width:88,height:122,borderRadius:radii.md,backgroundColor:colors.border},titleRow:{gap:6},title:{fontSize:16,fontWeight:'800',color:colors.textPrimary},author:{fontSize:11,color:colors.textSecondary,marginTop:5},price:{fontSize:15,fontWeight:'800',color:colors.primary,marginTop:10},preview:{backgroundColor:colors.primary,borderRadius:radii.pill,padding:9,alignItems:'center',marginTop:10},previewText:{fontSize:11,color:'#fff',fontWeight:'800'},sectionTitle:{...typography.h2,fontSize:15,marginTop:spacing.xl,marginBottom:spacing.md},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},stat:{backgroundColor:colors.card,borderRadius:radii.lg,padding:12,width:'31%',minHeight:68},statValue:{fontSize:14,fontWeight:'800',color:colors.textPrimary},statLabel:{fontSize:9.5,color:colors.textSecondary,marginTop:4},card:{backgroundColor:colors.card,borderRadius:radii.xl,padding:spacing.md},funnel:{marginBottom:10},funnelLabel:{fontSize:10.5,color:colors.textSecondary},bar:{height:5,backgroundColor:colors.primary,borderRadius:3,marginTop:4},funnelValue:{fontSize:10,fontWeight:'700',position:'absolute',right:0},insight:{fontSize:11,color:colors.textSecondary,lineHeight:17},insightRow:{flexDirection:'row',gap:8,marginVertical:10},action:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:13,borderBottomWidth:1,borderBottomColor:colors.border},actionLabel:{fontSize:12.5,fontWeight:'600',color:colors.textPrimary,flex:1}});
