import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/types';
import { earnService, type PdfMetadata, type PdfPricingModel } from '../services/api/earn.service';
import { colors, radii, spacing, typography } from '../theme';

type Props=NativeStackScreenProps<RootStackParamList,'PdfEditor'>;
type Form={title:string;description:string;price:string;currency:string;image:string;metadata:PdfMetadata};
const PRICING:{key:PdfPricingModel;label:string}[]=[['free','Completely free'],['one-time','One-time purchase'],['pay-what-you-want','Pay what you want'],['preview-paid','Free preview + paid access'],['membership','Included in membership'],['bundle','Product bundle'],['subscription','Subscription'],['promotion','Promotional price'],['launch-discount','Launch discount'],['limited-free','Free for limited period'],['coupon','Coupon code']].map(([key,label])=>({key:key as PdfPricingModel,label}));
const PREVIEWS=['First 3 pages','First 5 pages','First 10 pages','First chapter','Selected pages','Selected chapters','Percentage','Custom range'];
const DELIVERY=['App reader','Browser reader','Download to device','Online and offline','Permanent access','Limited-period access','Automatic edition updates'];

export default function PdfEditorScreen({route,navigation}:Props){
  const {pdfId,mode='upload'}=route.params||{};
  const [form,setForm]=useState<Form>({title:'',description:'',price:'0',currency:'USD',image:'',metadata:{author:'',language:'English',pricingModel:'preview-paid',previewMode:'First 5 pages',showToc:true,searchPreview:true,watermark:true,allowCopy:false,previewLocation:'app',delivery:['App reader','Permanent access'],deviceAccess:'account',promoImages:[],coAuthors:[],tags:[]}});
  const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(Boolean(pdfId));
  const meta=(patch:Partial<PdfMetadata>)=>setForm(v=>({...v,metadata:{...v.metadata,...patch}}));
  useEffect(()=>{if(!pdfId)return;earnService.getAsset(pdfId).then(a=>setForm({title:a.title,description:a.description||'',price:String(a.price||0),currency:a.currency||'USD',image:a.image||'',metadata:a.metadata as PdfMetadata||{}})).catch(e=>Alert.alert('Unable to load PDF',e.message)).finally(()=>setLoading(false));},[pdfId]);
  const pickPdf=async()=>{const result=await DocumentPicker.getDocumentAsync({type:'application/pdf',copyToCacheDirectory:true});if(result.canceled)return;try{setBusy(true);const f=result.assets[0];const uploaded=await earnService.uploadPdf({uri:f.uri,name:f.name,mimeType:f.mimeType});meta({fileUrl:uploaded.fileUrl,fileName:uploaded.fileName,fileSize:uploaded.fileSize});}catch(e){Alert.alert('Upload failed',(e as Error).message);}finally{setBusy(false);}};
  const pickImage=async(promo=false)=>{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.85});if(result.canceled)return;const uri=result.assets[0].uri;if(promo)meta({promoImages:[...(form.metadata.promoImages||[]),uri].slice(0,10)});else setForm(v=>({...v,image:uri}));};
  const save=async(status:'draft'|'published')=>{if(!form.title.trim())return Alert.alert('Title required','Enter a PDF title.');if(mode==='upload'&&!pdfId&&!form.metadata.fileUrl)return Alert.alert('PDF required','Select and upload a PDF file.');try{setBusy(true);const value={subtype:mode,title:form.title.trim(),description:form.description.trim(),price:Number(form.price)||0,currency:form.currency,image:form.image||undefined,status,metadata:form.metadata};const asset=pdfId?await earnService.updateAsset(pdfId,value):await earnService.createAsset({kind:'pdf',...value});navigation.replace('PdfDashboard',{pdfId:asset.id});}catch(e){Alert.alert('Unable to save',(e as Error).message);}finally{setBusy(false);}};
  if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}} color={colors.primary}/></SafeAreaView>;
  return <SafeAreaView style={s.safe} edges={['top']}><Header title={pdfId?'Edit PDF':'Create PDF'} back={navigation.goBack}/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text style={s.lead}>{mode==='ai'?'Generate and refine your digital book with AI.':mode==='manuscript'?'Upload a manuscript and format it as a professional digital book.':'Add the document, storefront information, preview and selling rules.'}</Text>
    <Section title="PDF file"><TouchableOpacity style={s.upload} onPress={pickPdf}><Ionicons name={form.metadata.fileUrl?'checkmark-circle':'cloud-upload-outline'} size={25} color={colors.primary}/><View style={{flex:1}}><Text style={s.uploadTitle}>{form.metadata.fileName||'Select a PDF document'}</Text><Text style={s.hint}>{form.metadata.fileSize?`${(form.metadata.fileSize/1048576).toFixed(1)} MB uploaded`:'PDF, up to 100 MB'}</Text></View></TouchableOpacity></Section>
    <Section title="Book information"><Field label="PDF title" value={form.title} set={title=>setForm(v=>({...v,title}))}/><Field label="Subtitle" value={form.metadata.subtitle||''} set={subtitle=>meta({subtitle})}/><Field label="Author name" value={form.metadata.author||''} set={author=>meta({author})}/><Field label="Co-authors (comma separated)" value={(form.metadata.coAuthors||[]).join(', ')} set={v=>meta({coAuthors:v.split(',').map(x=>x.trim()).filter(Boolean)})}/><Field label="Description" value={form.description} set={description=>setForm(v=>({...v,description}))} multiline/><Field label="Short summary" value={form.metadata.summary||''} set={summary=>meta({summary})} multiline/><Row><Field half label="Category" value={form.metadata.category||''} set={category=>meta({category})}/><Field half label="Subcategory" value={form.metadata.subcategory||''} set={subcategory=>meta({subcategory})}/></Row><Field label="Tags (comma separated)" value={(form.metadata.tags||[]).join(', ')} set={v=>meta({tags:v.split(',').map(x=>x.trim()).filter(Boolean)})}/><Row><Field half label="Language" value={form.metadata.language||''} set={language=>meta({language})}/><Field half label="Pages" value={String(form.metadata.pages||'')} set={v=>meta({pages:Number(v)||undefined})} numeric/></Row><Row><Field half label="Publication date" value={form.metadata.publicationDate||''} set={publicationDate=>meta({publicationDate})}/><Field half label="Edition" value={form.metadata.edition||''} set={edition=>meta({edition})}/></Row><Field label="Publisher" value={form.metadata.publisher||''} set={publisher=>meta({publisher})}/><Field label="Copyright information" value={form.metadata.copyright||''} set={copyright=>meta({copyright})}/><Row><Field half label="ISBN" value={form.metadata.isbn||''} set={isbn=>meta({isbn})}/><Field half label="Content rating" value={form.metadata.contentRating||''} set={contentRating=>meta({contentRating})}/></Row><Field label="Target audience" value={form.metadata.targetAudience||''} set={targetAudience=>meta({targetAudience})}/></Section>
    <Section title="Cover and promotional images"><TouchableOpacity style={s.coverPicker} onPress={()=>pickImage(false)}>{form.image?<Image source={{uri:form.image}} style={s.cover}/>:<><Ionicons name="image-outline" size={25} color={colors.primary}/><Text style={s.link}>Upload or design cover</Text></>}</TouchableOpacity><TouchableOpacity style={s.outline} onPress={()=>pickImage(true)}><Text style={s.outlineText}>Add promotional image ({form.metadata.promoImages?.length||0}/10)</Text></TouchableOpacity><View style={s.thumbs}>{form.metadata.promoImages?.map((x,i)=><Image key={`${x}-${i}`} source={{uri:x}} style={s.thumb}/>)}</View><Text style={s.hint}>Template and AI cover generation are available through “Generate cover” after the draft is saved.</Text></Section>
    <Section title="Free preview"><ChoiceGrid values={PREVIEWS} selected={form.metadata.previewMode||''} onSelect={previewMode=>meta({previewMode})}/><Field label="Pages, chapters, percentage or custom range" value={form.metadata.previewValue||''} set={previewValue=>meta({previewValue})}/><Toggle label="Show table of contents" value={!!form.metadata.showToc} set={showToc=>meta({showToc})}/><Toggle label="Allow search in preview" value={!!form.metadata.searchPreview} set={searchPreview=>meta({searchPreview})}/><Toggle label="Watermark preview pages" value={!!form.metadata.watermark} set={watermark=>meta({watermark})}/><Toggle label="Restrict screenshots where supported" value={!!form.metadata.restrictScreenshots} set={restrictScreenshots=>meta({restrictScreenshots})}/><Toggle label="Allow copying text" value={!!form.metadata.allowCopy} set={allowCopy=>meta({allowCopy})}/><Toggle label="Require app to continue" value={!!form.metadata.requireApp} set={requireApp=>meta({requireApp})}/><Text style={s.label}>Preview opens in</Text><ChoiceGrid values={['app','browser']} selected={form.metadata.previewLocation||'app'} onSelect={v=>meta({previewLocation:v as 'app'|'browser'})}/></Section>
    <Section title="Pricing"><ChoiceGrid values={PRICING.map(x=>x.label)} selected={PRICING.find(x=>x.key===form.metadata.pricingModel)?.label||''} onSelect={label=>meta({pricingModel:PRICING.find(x=>x.label===label)?.key})}/><Row><Field half label="Selling price" value={form.price} set={price=>setForm(v=>({...v,price}))} numeric/><Field half label="Currency" value={form.currency} set={currency=>setForm(v=>({...v,currency:currency.toUpperCase()}))}/></Row><Row><Field half label="Original price" value={String(form.metadata.originalPrice||'')} set={v=>meta({originalPrice:Number(v)||undefined})} numeric/><Field half label="Discounted price" value={String(form.metadata.discountPrice||'')} set={v=>meta({discountPrice:Number(v)||undefined})} numeric/></Row><Row><Field half label="Discount starts" value={form.metadata.discountStart||''} set={discountStart=>meta({discountStart})}/><Field half label="Discount ends" value={form.metadata.discountEnd||''} set={discountEnd=>meta({discountEnd})}/></Row><Field label="Tax setting" value={form.metadata.taxMode||''} set={taxMode=>meta({taxMode})}/></Section>
    <Section title="Access and delivery"><ChoiceGrid multi values={DELIVERY} selectedMany={form.metadata.delivery||[]} onSelect={v=>meta({delivery:(form.metadata.delivery||[]).includes(v)?form.metadata.delivery?.filter(x=>x!==v):[...(form.metadata.delivery||[]),v]})}/><Text style={s.label}>Device access</Text><ChoiceGrid values={['one','multiple','account']} selected={form.metadata.deviceAccess||'account'} onSelect={v=>meta({deviceAccess:v as PdfMetadata['deviceAccess']})}/></Section>
    <View style={s.actions}><TouchableOpacity style={s.draft} disabled={busy} onPress={()=>save('draft')}><Text style={s.draftText}>Save draft</Text></TouchableOpacity><TouchableOpacity style={s.publish} disabled={busy} onPress={()=>save('published')}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.publishText}>Publish PDF</Text>}</TouchableOpacity></View>
  </ScrollView></SafeAreaView>;
}

function Header({title,back}:{title:string;back:()=>void}){return <View style={s.header}><TouchableOpacity onPress={back}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><Text style={s.headerTitle}>{title}</Text><View style={{width:23}}/></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Row({children}:{children:React.ReactNode}){return <View style={s.row}>{children}</View>}
function Field({label,value,set,multiline,half,numeric}:{label:string;value:string;set:(v:string)=>void;multiline?:boolean;half?:boolean;numeric?:boolean}){return <View style={[s.field,half&&{flex:1}]}><Text style={s.label}>{label}</Text><TextInput style={[s.input,multiline&&s.multiline]} value={value} onChangeText={set} multiline={multiline} keyboardType={numeric?'decimal-pad':'default'} placeholder={label} placeholderTextColor={colors.textMuted}/></View>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <View style={s.toggle}><Text style={s.toggleLabel}>{label}</Text><Switch value={value} onValueChange={set} trackColor={{true:colors.primary}}/></View>}
function ChoiceGrid({values,selected,onSelect,multi,selectedMany=[]}:{values:string[];selected?:string;onSelect:(v:string)=>void;multi?:boolean;selectedMany?:string[]}){return <View style={s.choices}>{values.map(v=>{const active=multi?selectedMany.includes(v):selected===v;return <TouchableOpacity key={v} style={[s.chip,active&&s.chipActive]} onPress={()=>onSelect(v)}><Text style={[s.chipText,active&&s.chipTextActive]}>{v}</Text></TouchableOpacity>})}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.lg},headerTitle:{...typography.h2,color:colors.textPrimary},content:{padding:spacing.lg,paddingBottom:50},lead:{fontSize:12,color:colors.textSecondary,lineHeight:18},section:{backgroundColor:colors.card,borderRadius:radii.xl,padding:spacing.lg,marginTop:spacing.lg},sectionTitle:{fontSize:16,fontWeight:'800',color:colors.textPrimary,marginBottom:spacing.md},field:{marginBottom:spacing.md},label:{fontSize:11,fontWeight:'700',color:colors.textSecondary,marginBottom:6},input:{borderWidth:1,borderColor:colors.border,borderRadius:radii.md,paddingHorizontal:12,paddingVertical:11,color:colors.textPrimary,fontSize:13},multiline:{minHeight:82,textAlignVertical:'top'},row:{flexDirection:'row',gap:spacing.sm},upload:{flexDirection:'row',alignItems:'center',gap:spacing.md,borderWidth:1.5,borderStyle:'dashed',borderColor:colors.primary,borderRadius:radii.lg,padding:spacing.lg},uploadTitle:{fontSize:13,fontWeight:'800',color:colors.textPrimary},hint:{fontSize:10.5,color:colors.textSecondary,marginTop:4,lineHeight:15},coverPicker:{height:150,borderWidth:1.5,borderStyle:'dashed',borderColor:colors.border,borderRadius:radii.lg,alignItems:'center',justifyContent:'center',gap:7,overflow:'hidden'},cover:{width:'100%',height:'100%',resizeMode:'cover'},link:{fontSize:12,fontWeight:'700',color:colors.primary},outline:{borderWidth:1,borderColor:colors.primary,borderRadius:radii.pill,padding:11,alignItems:'center',marginTop:spacing.md},outlineText:{color:colors.primary,fontWeight:'700',fontSize:12},thumbs:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:8},thumb:{width:48,height:48,borderRadius:8},choices:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:spacing.md},chip:{borderWidth:1,borderColor:colors.border,borderRadius:radii.pill,paddingHorizontal:11,paddingVertical:8},chipActive:{backgroundColor:'#FFF0E8',borderColor:colors.primary},chipText:{fontSize:10.5,color:colors.textSecondary,fontWeight:'600'},chipTextActive:{color:colors.primary},toggle:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',minHeight:42,borderBottomWidth:1,borderBottomColor:colors.border},toggleLabel:{fontSize:12,color:colors.textPrimary,flex:1},actions:{flexDirection:'row',gap:spacing.sm,marginTop:spacing.xl},draft:{flex:1,borderWidth:1,borderColor:colors.primary,borderRadius:radii.pill,padding:14,alignItems:'center'},draftText:{color:colors.primary,fontWeight:'800'},publish:{flex:1,backgroundColor:colors.primary,borderRadius:radii.pill,padding:14,alignItems:'center'},publishText:{color:'#fff',fontWeight:'800'}});
