import React, { useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/types';
import { earnService, type EarnAsset, type PdfMetadata } from '../services/api/earn.service';
import { colors, radii, spacing, typography } from '../theme';
type Props=NativeStackScreenProps<RootStackParamList,'PdfReviews'>;
export default function PdfReviewsScreen({route,navigation}:Props){const [pdf,setPdf]=useState<EarnAsset|null>(null);const [reply,setReply]=useState<Record<string,string>>({});useEffect(()=>{earnService.getAsset(route.params.pdfId).then(setPdf).catch(e=>Alert.alert('Unable to load reviews',e.message));},[route.params.pdfId]);const md=(pdf?.metadata||{}) as PdfMetadata;const reviews=md.reviews||[];const average=reviews.length?reviews.reduce((n,r)=>n+r.rating,0)/reviews.length:0;const save=async(id:string)=>{if(!pdf||!reply[id]?.trim())return;const next=reviews.map(r=>r.id===id?{...r,reply:reply[id].trim()}:r);setPdf(await earnService.updateAsset(pdf.id,{metadata:{...md,reviews:next}}));};return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={navigation.goBack}><Ionicons name="chevron-back" size={22}/></TouchableOpacity><Text style={s.title}>Reviews and ratings</Text><View style={{width:22}}/></View><ScrollView contentContainerStyle={s.content}><View style={s.summary}><Text style={s.big}>{average.toFixed(1)}</Text><Text style={s.stars}>★★★★★</Text><Text style={s.muted}>{reviews.length} verified reader reviews</Text>{[5,4,3,2,1].map(x=><View key={x} style={s.distribution}><Text style={s.small}>{x}★</Text><View style={s.track}><View style={[s.fill,{width:`${reviews.length?reviews.filter(r=>r.rating===x).length/reviews.length*100:0}%`}]} /></View></View>)}</View>{reviews.map(r=><View key={r.id} style={s.card}><View style={s.reviewTop}><Text style={s.name}>{r.author}</Text><Text style={s.stars}>{'★'.repeat(r.rating)}</Text></View><Text style={s.review}>{r.text}</Text><Text style={s.muted}>{new Date(r.createdAt).toLocaleDateString()} · Verified purchase</Text>{r.reply?<View style={s.creatorReply}><Text style={s.name}>Creator reply</Text><Text style={s.review}>{r.reply}</Text></View>:<View style={s.replyRow}><TextInput style={s.input} placeholder="Reply to this review" value={reply[r.id]||''} onChangeText={v=>setReply(x=>({...x,[r.id]:v}))}/><TouchableOpacity onPress={()=>save(r.id)}><Text style={s.send}>Reply</Text></TouchableOpacity></View>}<TouchableOpacity onPress={()=>Alert.alert('Review reported','We will review this content.')}><Text style={s.report}>Report abusive review</Text></TouchableOpacity></View>)}{!reviews.length?<Text style={s.empty}>Purchased readers’ ratings and reviews will appear here.</Text>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.lg},title:{...typography.h2},content:{padding:spacing.lg},summary:{backgroundColor:'#fff',borderRadius:radii.xl,padding:20,alignItems:'center'},big:{fontSize:34,fontWeight:'900'},stars:{color:'#FFB020',fontWeight:'800'},muted:{fontSize:10.5,color:colors.textSecondary,marginTop:5},distribution:{flexDirection:'row',alignItems:'center',width:'100%',gap:8,marginTop:7},small:{fontSize:10},track:{height:5,backgroundColor:colors.border,flex:1,borderRadius:3},fill:{height:5,backgroundColor:'#FFB020',borderRadius:3},card:{backgroundColor:'#fff',borderRadius:radii.xl,padding:16,marginTop:12},reviewTop:{flexDirection:'row',justifyContent:'space-between'},name:{fontSize:12,fontWeight:'800'},review:{fontSize:12,lineHeight:18,color:colors.textPrimary,marginTop:6},creatorReply:{backgroundColor:colors.background,borderRadius:radii.md,padding:10,marginTop:10},replyRow:{flexDirection:'row',alignItems:'center',gap:8,marginTop:10},input:{borderWidth:1,borderColor:colors.border,borderRadius:radii.md,padding:9,flex:1,fontSize:11},send:{fontWeight:'800',color:colors.primary},report:{fontSize:10,color:'#D33',marginTop:12},empty:{textAlign:'center',color:colors.textSecondary,marginTop:35}});
