import React, { useRef, useState } from 'react';
import { Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/types';
import { colors } from '../theme';
type Props=NativeStackScreenProps<RootStackParamList,'VideoRecorder'>;
export default function VideoRecorderScreen({navigation}:Props){const camera=useRef<CameraView>(null);const [permission,request]=useCameraPermissions();const [recording,setRecording]=useState(false);const [facing,setFacing]=useState<'front'|'back'>('back');if(!permission)return <View/>;if(!permission.granted)return <SafeAreaView style={s.permission}><Text>Camera and microphone permission are required to record video.</Text><TouchableOpacity style={s.allow} onPress={request}><Text style={s.allowText}>Allow camera</Text></TouchableOpacity></SafeAreaView>;const toggle=async()=>{if(recording){camera.current?.stopRecording();return;}try{setRecording(true);const result=await camera.current?.recordAsync({maxDuration:1800});if(result?.uri)navigation.replace('VideoEditor',{mode:'record',fileUri:result.uri});}catch(e){Alert.alert('Recording failed',(e as Error).message)}finally{setRecording(false)}};return <View style={s.safe}><CameraView ref={camera} style={StyleSheet.absoluteFill} facing={facing} mode="video" mute={false}/><SafeAreaView style={s.overlay}><View style={s.top}><TouchableOpacity onPress={navigation.goBack}><Ionicons name="close" size={28} color="#fff"/></TouchableOpacity><Text style={s.title}>{recording?'Recording…':'Record video'}</Text><TouchableOpacity onPress={()=>setFacing(x=>x==='back'?'front':'back')}><Ionicons name="camera-reverse-outline" size={27} color="#fff"/></TouchableOpacity></View><TouchableOpacity style={[s.record,recording&&s.recording]} onPress={toggle}><View style={s.inner}/></TouchableOpacity></SafeAreaView></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#000'},overlay:{flex:1,justifyContent:'space-between',alignItems:'center',paddingBottom:35},top:{width:'100%',paddingHorizontal:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:'#fff',fontWeight:'800'},record:{width:76,height:76,borderRadius:38,borderWidth:5,borderColor:'#fff',alignItems:'center',justifyContent:'center'},recording:{borderColor:'#ff5252'},inner:{width:55,height:55,borderRadius:28,backgroundColor:'#ff5252'},permission:{flex:1,alignItems:'center',justifyContent:'center',padding:30,gap:20},allow:{backgroundColor:colors.primary,padding:14,borderRadius:30},allowText:{color:'#fff',fontWeight:'800'}});
