import React, { useEffect, useState } from 'react';
import { Alert, Image, ScrollView, Share, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useVideoPlayer, VideoView } from 'expo-video';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/types';
import { earnService, type EarnAsset, type VideoMetadata } from '../services/api/earn.service';
import { colors, radii } from '../theme';

type Props=NativeStackScreenProps<RootStackParamList,'VideoPlayer'>;

function Player({video,preview,navigation}:{video:EarnAsset;preview:boolean;navigation:Props['navigation']}) {
  const md=video.metadata as VideoMetadata||{};
  const uri=md.fileUrl||md.trailerUrl||'';
  const player=useVideoPlayer(uri,p=>{p.timeUpdateEventInterval=1;p.play()});
  const [position,setPosition]=useState(0);
  const [locked,setLocked]=useState(false);
  const [saved,setSaved]=useState(false);
  const [comment,setComment]=useState('');
  const limit=Number(md.previewSeconds||60);
  useEffect(()=>{const sub=player.addListener('timeUpdate',({currentTime})=>{setPosition(currentTime);if(preview&&md.monetization!=='free'&&limit>0&&currentTime>=limit){player.pause();setLocked(true)}});return()=>sub.remove()},[player,preview,limit,md.monetization]);
  const postComment=async()=>{if(!comment.trim())return;const comments=[...(md.comments||[]),{id:`comment-${Date.now()}`,text:comment.trim(),author:'Creator',createdAt:new Date().toISOString()}];await earnService.updateAsset(video.id,{metadata:{...md,comments}});setComment('');Alert.alert('Comment posted')};
  return <SafeAreaView style={s.safe}>
    <View style={s.header}><TouchableOpacity onPress={navigation.goBack}><Ionicons name="chevron-back" size={23} color="#fff"/></TouchableOpacity><Text style={s.headerTitle} numberOfLines={1}>{video.title}</Text><TouchableOpacity onPress={()=>Share.share({message:`Watch ${video.title}: teamcal://video/${video.id}`})}><Ionicons name="share-outline" size={22} color="#fff"/></TouchableOpacity></View>
    <View style={s.playerWrap}>{uri?<VideoView player={player} style={s.player} nativeControls fullscreenOptions={{enable:true}} allowsPictureInPicture contentFit="contain"/>:<View style={s.missing}><Image source={{uri:video.image||`https://picsum.photos/seed/${video.id}/640/360`}} style={s.player}/><Text style={s.missingText}>Video file is still processing</Text></View>}{locked&&<View style={s.paywall}><Text style={s.payTitle}>Unlock {video.title}</Text><Text style={s.payDesc}>{md.summary||video.description}</Text><Text style={s.payPrice}>{video.currency} {Number(video.price).toFixed(2)}</Text><Text style={s.payDesc}>{Math.max(0,Math.round(Number(md.duration||0)-position))} seconds remaining</Text><TouchableOpacity style={s.buy} onPress={()=>Alert.alert('Secure purchase','Payment completion unlocks access using the creator’s settings.')}><Text style={s.buyText}>Unlock Full Video</Text></TouchableOpacity>{md.seriesName&&<TouchableOpacity style={s.secondary}><Text style={s.secondaryText}>Buy Series</Text></TouchableOpacity>}<TouchableOpacity style={s.secondary}><Text style={s.secondaryText}>Join Membership</Text></TouchableOpacity></View>}</View>
    <ScrollView contentContainerStyle={s.content}><Text style={s.title}>{video.title}</Text><Text style={s.meta}>{md.seriesName?`${md.seriesName} · `:''}{Number(video.metrics?.views||0)} views · {Math.round(position)}s watched</Text><Text style={s.desc}>{video.description}</Text><View style={s.actions}>{[['heart-outline','Like'],[saved?'bookmark':'bookmark-outline','Save'],['share-outline','Share'],['flag-outline','Report']].map(([icon,label])=><TouchableOpacity key={label} style={s.action} onPress={()=>label==='Save'?setSaved(!saved):label==='Share'?Share.share({message:`teamcal://video/${video.id}`}):Alert.alert(label,label==='Report'?'Thanks. We will review this video.':`${label} recorded.`)}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={20} color={colors.primary}/><Text style={s.actionLabel}>{label}</Text></TouchableOpacity>)}</View>
      {md.transcript&&<><Text style={s.section}>Transcript</Text><Text style={s.desc}>{md.transcript}</Text></>}
      {!!md.episodes?.length&&<><Text style={s.section}>Episodes</Text>{md.episodes.map((e,i)=><TouchableOpacity key={e.id} style={s.episode}><Text style={s.epNo}>{i+1}</Text><View style={{flex:1}}><Text style={s.epTitle}>{e.title}</Text><Text style={s.meta}>Season {e.season||1} · {e.free?'Free':'Paid'}</Text></View><Ionicons name="play-circle-outline" size={24}/></TouchableOpacity>)}</>}
      {md.commentsEnabled&&<><Text style={s.section}>Comments</Text><View style={s.commentRow}><TextInput style={s.input} placeholder="Join the discussion" value={comment} onChangeText={setComment}/><TouchableOpacity onPress={postComment}><Text style={s.post}>Post</Text></TouchableOpacity></View>{md.comments?.map(c=><View key={c.id} style={s.comment}><Text style={s.epTitle}>{c.author}</Text><Text style={s.desc}>{c.text}</Text></View>)}</>}
      <Text style={s.section}>More from this creator</Text><Text style={s.desc}>Related videos, PDFs, blog posts, memberships and products appear here.</Text>
    </ScrollView>
  </SafeAreaView>
}

export default function VideoPlayerScreen({route,navigation}:Props){const [video,setVideo]=useState<EarnAsset|null>(null);useEffect(()=>{earnService.getAsset(route.params.videoId).then(setVideo).catch(e=>Alert.alert('Unable to play',e.message))},[route.params.videoId]);return video?<Player video={video} preview={route.params.preview!==false} navigation={navigation}/>:<SafeAreaView style={s.safe}><Text style={s.loading}>Loading video…</Text></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#10131C'},loading:{color:'#fff',textAlign:'center',marginTop:100},header:{height:50,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:16},headerTitle:{flex:1,color:'#fff',fontWeight:'800',textAlign:'center'},playerWrap:{height:230,backgroundColor:'#000'},player:{width:'100%',height:'100%'},missing:{width:'100%',height:'100%'},missingText:{position:'absolute',alignSelf:'center',top:100,color:'#fff',fontWeight:'800'},paywall:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'rgba(10,12,18,.94)',alignItems:'center',justifyContent:'center',padding:22},payTitle:{fontSize:17,color:'#fff',fontWeight:'900',textAlign:'center'},payDesc:{fontSize:11,color:'#C7C9D0',textAlign:'center',marginTop:6},payPrice:{fontSize:20,color:colors.primary,fontWeight:'900',marginTop:8},buy:{backgroundColor:colors.primary,borderRadius:30,paddingVertical:11,paddingHorizontal:24,marginTop:10},buyText:{color:'#fff',fontWeight:'800'},secondary:{marginTop:7},secondaryText:{color:'#fff',fontWeight:'700',fontSize:11},content:{backgroundColor:colors.background,padding:16,paddingBottom:40},title:{fontSize:18,fontWeight:'900'},meta:{fontSize:10.5,color:colors.textSecondary,marginTop:4},desc:{fontSize:12,color:colors.textSecondary,lineHeight:18,marginTop:7},actions:{flexDirection:'row',justifyContent:'space-around',marginTop:15,paddingVertical:10,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border},action:{alignItems:'center',gap:3},actionLabel:{fontSize:9.5},section:{fontSize:15,fontWeight:'800',marginTop:20,marginBottom:8},episode:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'#fff',padding:10,borderRadius:radii.md,marginBottom:7},epNo:{width:27,height:27,borderRadius:14,textAlign:'center',paddingTop:6,backgroundColor:'#FFF0E8',color:colors.primary,fontWeight:'800'},epTitle:{fontSize:12,fontWeight:'800'},commentRow:{flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,padding:10},post:{color:colors.primary,fontWeight:'800'},comment:{backgroundColor:'#fff',borderRadius:radii.md,padding:10,marginTop:7}});
