import React,{useCallback,useState} from 'react';
import {ScrollView,StatusBar,StyleSheet,Text,TouchableOpacity,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {Ionicons} from '@expo/vector-icons';import {useFocusEffect,useNavigation} from '@react-navigation/native';import type {NativeStackNavigationProp} from '@react-navigation/native-stack';
import SegmentedControl from '../components/SegmentedControl';import ExerciseRow from '../components/ExerciseRow';import {colors,radii,shadow,spacing,typography} from '../theme';import {workoutTabs} from '../data/workoutsData';import {useTodayWorkout,useWorkouts} from '../hooks/useWorkouts';import {useApiQuery} from '../hooks/useApiQuery';import {workoutsService,type WorkoutLog} from '../services/api/workouts.service';import type {RootStackParamList} from '../navigation/types';
export default function WorkoutsScreen(){const [tab,setTab]=useState(workoutTabs[0]);const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>();const {workout:todayWorkout}=useTodayWorkout();const {workouts}=useWorkouts();const history=useApiQuery(()=>workoutsService.getHistory(),[] as WorkoutLog[],[]);useFocusEffect(useCallback(()=>{if(tab==='History')history.refetch();},[tab,history.refetch]));
const start=(w:{id?:string;title:string;duration?:number;exercises:{id:string;name:string;detail:string}[]})=>navigation.navigate('WorkoutSession',{workout:w});
return <SafeAreaView style={s.safe} edges={['top']}><StatusBar barStyle="dark-content" backgroundColor={colors.background}/><View style={s.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={22}/></TouchableOpacity><Text style={s.pageTitle}>Workouts</Text><View style={{width:22}}/></View><View style={s.tabs}><SegmentedControl options={workoutTabs} value={tab} onChange={setTab} variant="pill"/></View><ScrollView contentContainerStyle={s.content}>
{tab==='Plan'&&<><WorkoutCard title={todayWorkout.title} subtitle={todayWorkout.subtitle} exercises={todayWorkout.exercises}/><TouchableOpacity style={s.start} onPress={()=>start({title:todayWorkout.title,exercises:todayWorkout.exercises})}><Text style={s.startText}>Start Workout</Text></TouchableOpacity></>}
{tab==='Library'&&<View style={{gap:spacing.md}}>{workouts.map(w=><TouchableOpacity key={w.id} style={[s.card,shadow.card]} onPress={()=>start({id:w.id,title:w.title,duration:w.duration,exercises:w.exercises})}><View style={s.cardHead}><View><Text style={s.workoutTitle}>{w.title}</Text><Text style={s.subtitle}>{w.duration} min · {w.difficulty} · {w.category}</Text></View><Ionicons name="play-circle" size={30} color={colors.primary}/></View><Text style={s.exerciseCount}>{w.exercises.length} exercises</Text></TouchableOpacity>)}</View>}
{tab==='History'&&<View style={{gap:spacing.md}}>{history.data.map(log=><View style={[s.card,shadow.soft]} key={log.id}><Text style={s.workoutTitle}>{log.title}</Text><Text style={s.subtitle}>{new Date(log.started_at).toLocaleDateString()} · {log.duration||Math.max(1,Math.round((log.ended_at-log.started_at)/60000))} min</Text><Text style={s.exerciseCount}>{log.exercises?.length||0} exercises completed</Text></View>)}{!history.loading&&!history.data.length&&<Text style={s.empty}>Complete a workout to see it here.</Text>}</View>}
</ScrollView></SafeAreaView>}
function WorkoutCard({title,subtitle,exercises}:{title:string;subtitle:string;exercises:{id:string;name:string;detail:string}[]}){return <View style={[s.card,shadow.card]}><Text style={s.workoutTitle}>{title}</Text><Text style={s.subtitle}>{subtitle}</Text><View style={{marginTop:spacing.md}}>{exercises.map(e=><ExerciseRow key={e.id} name={e.name} detail={e.detail}/>)}</View></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.lg,paddingTop:spacing.sm},pageTitle:{...typography.h2},tabs:{paddingHorizontal:spacing.lg,marginTop:spacing.md},content:{padding:spacing.lg,paddingBottom:spacing.xxl},card:{backgroundColor:colors.card,borderRadius:radii.xl,padding:spacing.lg},cardHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},workoutTitle:{fontSize:16,fontWeight:'800',color:colors.textPrimary},subtitle:{fontSize:12,color:colors.textSecondary,marginTop:3,textTransform:'capitalize'},exerciseCount:{fontSize:12,fontWeight:'700',color:colors.primary,marginTop:spacing.md},start:{backgroundColor:colors.primary,borderRadius:radii.pill,paddingVertical:spacing.md,alignItems:'center',marginTop:spacing.lg},startText:{color:colors.white,fontWeight:'700',fontSize:15},empty:{textAlign:'center',color:colors.textMuted,marginTop:40}});
