import React,{useEffect,useState} from 'react';
import {Alert,StyleSheet,Text,TouchableOpacity,View,FlatList} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';import {Ionicons} from '@expo/vector-icons';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';import type {RootStackParamList} from '../navigation/types';
import {workoutsService} from '../services/api/workouts.service';import {colors,radii,spacing,typography} from '../theme';
type Props=NativeStackScreenProps<RootStackParamList,'WorkoutSession'>;
export default function WorkoutSessionScreen({route,navigation}:Props){const {workout}=route.params;const [startedAt]=useState(Date.now());const [now,setNow]=useState(Date.now());const [done,setDone]=useState<Record<string,boolean>>({});const [saving,setSaving]=useState(false);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);const seconds=Math.floor((now-startedAt)/1000);const time=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;const completed=Object.values(done).filter(Boolean).length;
const finish=async()=>{try{setSaving(true);await workoutsService.log({workoutId:workout.id,title:workout.title,duration:Math.max(1,Math.round(seconds/60)),exercises:workout.exercises,startedAt,endedAt:Date.now()});Alert.alert('Workout complete',`${completed}/${workout.exercises.length} exercises completed.`,[{text:'Done',onPress:()=>navigation.goBack()}]);}catch(e){Alert.alert('Unable to save workout',(e as Error).message);}finally{setSaving(false)}};
return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={()=>Alert.alert('Leave workout?','Your progress will not be saved.',[{text:'Stay',style:'cancel'},{text:'Leave',style:'destructive',onPress:()=>navigation.goBack()}])}><Ionicons name="close" size={24}/></TouchableOpacity><Text style={s.title}>{workout.title}</Text><Text style={s.timer}>{time}</Text></View><View style={s.progress}><View style={[s.fill,{width:`${workout.exercises.length?completed/workout.exercises.length*100:0}%`}]} /></View><Text style={s.count}>{completed} of {workout.exercises.length} completed</Text><FlatList data={workout.exercises} keyExtractor={x=>x.id} contentContainerStyle={s.list} renderItem={({item,index})=><TouchableOpacity style={[s.row,done[item.id]&&s.doneRow]} onPress={()=>setDone(v=>({...v,[item.id]:!v[item.id]}))}><View style={[s.number,done[item.id]&&s.doneNumber]}>{done[item.id]?<Ionicons name="checkmark" size={18} color={colors.white}/>:<Text>{index+1}</Text>}</View><View><Text style={s.name}>{item.name}</Text><Text style={s.detail}>{item.detail}</Text></View></TouchableOpacity>}/><TouchableOpacity style={s.finish} onPress={finish} disabled={saving}><Text style={s.finishText}>{saving?'Saving…':'Finish Workout'}</Text></TouchableOpacity></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:spacing.lg},title:{...typography.h2,flex:1,textAlign:'center'},timer:{fontWeight:'800',color:colors.primary,width:52},progress:{height:6,backgroundColor:colors.border,marginHorizontal:spacing.lg,borderRadius:3,overflow:'hidden'},fill:{height:6,backgroundColor:colors.success},count:{textAlign:'center',color:colors.textSecondary,marginTop:spacing.sm},list:{padding:spacing.lg,gap:spacing.sm},row:{flexDirection:'row',alignItems:'center',gap:spacing.md,backgroundColor:colors.card,padding:spacing.md,borderRadius:radii.lg},doneRow:{opacity:.65},number:{width:34,height:34,borderRadius:17,backgroundColor:colors.border,alignItems:'center',justifyContent:'center'},doneNumber:{backgroundColor:colors.success},name:{...typography.bodyBold,color:colors.textPrimary},detail:{...typography.caption,color:colors.textSecondary,marginTop:2},finish:{backgroundColor:colors.primary,padding:spacing.md,borderRadius:radii.pill,alignItems:'center',margin:spacing.lg},finishText:{color:colors.white,fontWeight:'800'}});
