import type { Exercise } from '../types/api';
import type { Recipe } from '../services/api/recipe.service';
import type { LegalDocumentKey } from '../data/legalDocuments';

export type RootStackParamList = {
  Onboarding: undefined;
  Login: undefined;
  SignUp: undefined;
  ForgotPassword: undefined;
  VerifyCode: { mode: 'signup' | 'reset'; email: string; verificationToken?: string };
  ResetPassword: { email: string; resetToken: string };
  MainTabs: undefined;
  CoachChat: undefined;
  ScanFood: { mode?: 'food' | 'barcode' | 'cook' } | undefined;
  Challenges: undefined;
  Leaderboards: undefined;
  MealPlanner: undefined;
  Workouts: undefined;
  Progress: undefined;
  PowerSquad: { groupId?: string } | undefined;
  Marketplace: undefined;
  Rewards: undefined;
  InviteFriends: undefined;
  Settings: undefined;
  EditProfile: undefined;
  ChangePassword: undefined;
  NotificationSettings: undefined;
  Privacy: undefined;
  HelpSupport: undefined;
  LegalDocument: { document: LegalDocumentKey };
  QuickLogEntry: { kind: string };
  GroceryList: undefined;
  GlobalSearch: { query?: string } | undefined;
  MealEditor: { date: string; meal?: { id: string; name: string; mealType: string; kcal: number; protein: number; carbs: number; fats: number } };
  WorkoutSession: { workout: { id?: string; title: string; duration?: number; exercises: Exercise[] } };
  Comments: { postId: string };
  CreateCommunity: undefined;
  CreateChallenge: { challengeId?: string } | undefined;
  ProfileCollection: { kind: 'measurements' | 'photos' | 'achievements' };
  MarketplaceDetail: { productId: string };
  MarketplaceOrders: undefined;
  NotificationsInbox: undefined;
  BlogDetail: { blogId: string };
  Water: undefined;
  Steps: undefined;
  Weight: undefined;
  Sleep: undefined;
  Fasting: undefined;
  Profile: undefined;
  BlogDashboard: { blogId: string };
  CreateBlog: undefined;
  AudienceEngine: { sourceLabel?: string; pdfId?:string; videoId?:string; membershipId?:string } | undefined;
  PdfEditor: { pdfId?:string; mode?:string } | undefined;
  PdfDashboard: { pdfId:string };
  PdfReader: { pdfId:string; preview?:boolean };
  PdfReviews: { pdfId:string };
  VideoEditor: { videoId?:string; mode?:string; fileUri?:string } | undefined;
  VideoDashboard: { videoId:string };
  VideoPlayer: { videoId:string; preview?:boolean };
  VideoRecorder: undefined;
  MembershipEditor: { membershipId?:string } | undefined;
  MembershipDashboard: { membershipId:string };
  MembershipPublic: { membershipId:string };
  MembershipCheckout: { membershipId:string; tierId?:string };
  DirectMessage: { userId: string; name: string; avatar?: string | null };
  Goals: undefined;
  ChallengeDetail: { challengeId: string };
  ChallengeInvite: { challengeId: string };
  MyRecipes: undefined;
  RecipeLibrary: undefined;
  CookMode: { recipe: Recipe };
  PeriodTracker: undefined;
  SupplementTracker: undefined;
  MoodJournal: undefined;
  LiveJournalCall: undefined;
  ArticleEditor: { blogId:string; articleId?:string; pickedCategory?:string; pickedTags?:string[]; insertText?:string };
  SelectCategory: { blogId:string; articleId?:string; current?:string };
  AddTags: { blogId:string; articleId?:string; current?:string[] };
  AIHelper: { blogId:string; articleId?:string; existingContent?:string };
  AudienceAccounts: undefined;
  BlogSettings: {blogId:string};
  UploadVideo: undefined;
  UploadMultiple: undefined;
  CreateSeries: undefined;
  CreateCourse: undefined;
  RecordVideoFlow: { fileUri?: string } | undefined;
  ImportFromCloud: undefined;
  UploadPdf: undefined;
  CreatePdf: undefined;
  AiGeneratePdf: undefined;
};

export type NoParamRoute = {
  [K in keyof RootStackParamList]: RootStackParamList[K] extends undefined ? K : never;
}[keyof RootStackParamList];

export type MainTabParamList = {
  Home: undefined;
  Explore: undefined;
  Community: undefined;
  Earn: undefined;
};
