import React from 'react';
import { Alert, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import StatusBadge from '../components/StatusBadge';
import { colors, radii, shadow, spacing } from '../../../theme';
import { audienceEngineGeneratedPosts } from '../../../data/earnData';

const SUGGESTIONS = ['Add a statistic', 'Shorten the caption', 'Add a CTA'];

type Props = {
  approvals: Record<string, 'Approved' | 'Needs Review'>;
  setApprovals: (v: Record<string, 'Approved' | 'Needs Review'>) => void;
  onNext: () => void;
  onBack: () => void;
};

export default function ReviewStep({ approvals, setApprovals, onNext, onBack }: Props) {
  const approveAll = () => {
    const next: Record<string, 'Approved' | 'Needs Review'> = {};
    audienceEngineGeneratedPosts.forEach((p) => (next[p.id] = 'Approved'));
    setApprovals(next);
  };

  const regenerateAll = () => Alert.alert('Regenerating', 'All posts are being regenerated with new AI variations.');

  return (
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <Text style={styles.title}>Review Your Content</Text>
      <Text style={styles.subtitle}>Review each post generated by AI. You can edit, regenerate or approve any post.</Text>

      <View style={{ gap: spacing.md }}>
        {audienceEngineGeneratedPosts.map((post) => {
          const status = approvals[post.id] ?? post.status;
          return (
            <View key={post.id} style={[styles.postCard, shadow.soft]}>
              <Image source={{ uri: post.thumbnail }} style={styles.postImage} />
              <View style={{ flex: 1 }}>
                <Text style={styles.postCaption} numberOfLines={2}>
                  {post.caption}
                </Text>
                <View style={styles.postMetaRow}>
                  <View style={styles.formatPill}>
                    <Text style={styles.formatPillText}>{post.format}</Text>
                  </View>
                  <StatusBadge status={status} />
                </View>
                <View style={styles.postActions}>
                  <TouchableOpacity onPress={() => Alert.alert('Coming soon', 'Post editing will be available soon.')}>
                    <Text style={styles.postActionText}>Edit</Text>
                  </TouchableOpacity>
                  <TouchableOpacity onPress={() => Alert.alert('Regenerating', `"${post.caption.slice(0, 30)}…" is being regenerated.`)}>
                    <Text style={styles.postActionText}>Regenerate</Text>
                  </TouchableOpacity>
                  <TouchableOpacity onPress={() => setApprovals({ ...approvals, [post.id]: 'Approved' })}>
                    <Text style={[styles.postActionText, { color: colors.success }]}>Approve</Text>
                  </TouchableOpacity>
                </View>
              </View>
            </View>
          );
        })}
      </View>

      <View style={[styles.suggestionsCard, shadow.soft]}>
        <View style={styles.suggestionsHeader}>
          <Ionicons name="bulb-outline" size={16} color={colors.primary} />
          <Text style={styles.suggestionsTitle}>AI Suggestions</Text>
        </View>
        <View style={styles.suggestionsRow}>
          {SUGGESTIONS.map((s) => (
            <TouchableOpacity key={s} style={styles.suggestionChip} onPress={() => Alert.alert('Coming soon', `${s} isn't available yet.`)}>
              <Text style={styles.suggestionChipText}>{s}</Text>
              <Ionicons name="add" size={12} color={colors.primary} />
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.footerRow}>
        <TouchableOpacity style={styles.secondaryBtn} onPress={onBack}>
          <Text style={styles.secondaryBtnText}>Back</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.outlineBtn} onPress={regenerateAll}>
          <Text style={styles.outlineBtnText}>Regenerate All</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.primaryBtn, { flex: 1 }]}
          onPress={() => {
            approveAll();
            onNext();
          }}
          activeOpacity={0.85}
        >
          <Text style={styles.primaryBtnText}>Approve All</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  title: { fontSize: 16, fontWeight: '800', color: colors.textPrimary },
  subtitle: { fontSize: 12, color: colors.textSecondary, marginTop: 4, marginBottom: spacing.lg, lineHeight: 17 },
  postCard: { flexDirection: 'row', gap: spacing.md, backgroundColor: colors.card, borderRadius: radii.xl, padding: spacing.md },
  postImage: { width: 56, height: 56, borderRadius: radii.md, backgroundColor: colors.border },
  postCaption: { fontSize: 12.5, fontWeight: '700', color: colors.textPrimary, lineHeight: 17 },
  postMetaRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: 6 },
  formatPill: { backgroundColor: colors.background, borderRadius: radii.pill, paddingHorizontal: 8, paddingVertical: 2 },
  formatPillText: { fontSize: 10, fontWeight: '700', color: colors.textSecondary },
  postActions: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.sm },
  postActionText: { fontSize: 11, fontWeight: '700', color: colors.textSecondary },
  suggestionsCard: { backgroundColor: colors.card, borderRadius: radii.xl, padding: spacing.lg, marginTop: spacing.lg },
  suggestionsHeader: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  suggestionsTitle: { fontSize: 13, fontWeight: '800', color: colors.textPrimary },
  suggestionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.sm },
  suggestionChip: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: colors.border, borderRadius: radii.pill, paddingHorizontal: spacing.md, paddingVertical: 6 },
  suggestionChipText: { fontSize: 11, fontWeight: '600', color: colors.textPrimary },
  footerRow: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xl, flexWrap: 'wrap' },
  secondaryBtn: { borderWidth: 1, borderColor: colors.border, borderRadius: radii.pill, paddingVertical: spacing.md, paddingHorizontal: spacing.lg, alignItems: 'center' },
  secondaryBtnText: { fontSize: 13, fontWeight: '700', color: colors.textPrimary },
  outlineBtn: { borderWidth: 1, borderColor: colors.primary, borderRadius: radii.pill, paddingVertical: spacing.md, paddingHorizontal: spacing.lg, alignItems: 'center' },
  outlineBtnText: { fontSize: 13, fontWeight: '700', color: colors.primary },
  primaryBtn: { backgroundColor: colors.primary, borderRadius: radii.pill, paddingVertical: spacing.md, alignItems: 'center' },
  primaryBtnText: { color: colors.white, fontWeight: '700', fontSize: 13 },
});
