import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { colors, radii, spacing, typography } from '../../../theme';

type Props={visible:boolean;heading:string;subtype:string;priceEnabled?:boolean;onClose:()=>void;onSubmit:(value:{title:string;description:string;price:number})=>Promise<void>};

export default function CreateAssetModal({visible,heading,subtype,priceEnabled=true,onClose,onSubmit}:Props){
  const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [price,setPrice]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(visible){setTitle('');setDescription('');setPrice('');setError('');}},[visible]);
  const save=async()=>{if(!title.trim()){setError('Enter a title.');return;}try{setBusy(true);setError('');await onSubmit({title:title.trim(),description:description.trim(),price:Number(price)||0});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}><Pressable style={s.card} onPress={()=>{}}><Text style={s.title}>{heading}</Text><Text style={s.meta}>{subtype}</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Title" placeholderTextColor={colors.textSecondary}/><TextInput style={[s.input,s.multiline]} value={description} onChangeText={setDescription} placeholder="Description" placeholderTextColor={colors.textSecondary} multiline/>{priceEnabled&&<TextInput style={s.input} value={price} onChangeText={setPrice} placeholder="Price (USD)" placeholderTextColor={colors.textSecondary} keyboardType="decimal-pad"/>}{error?<Text style={s.error}>{error}</Text>:null}<View style={s.actions}><TouchableOpacity style={s.secondary} onPress={onClose} disabled={busy}><Text style={s.secondaryText}>Cancel</Text></TouchableOpacity><TouchableOpacity style={s.primary} onPress={save} disabled={busy}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={s.primaryText}>Save Draft</Text>}</TouchableOpacity></View></Pressable></Pressable></Modal>;
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(14,24,44,.45)',alignItems:'center',justifyContent:'center',padding:spacing.lg},card:{width:'100%',maxWidth:430,backgroundColor:colors.card,borderRadius:radii.xl,padding:spacing.xl},title:{...typography.h2,color:colors.textPrimary},meta:{fontSize:12,color:colors.textSecondary,marginTop:4,marginBottom:spacing.lg},input:{borderWidth:1,borderColor:colors.border,borderRadius:radii.md,paddingHorizontal:spacing.md,paddingVertical:12,color:colors.textPrimary,marginBottom:spacing.sm},multiline:{height:82,textAlignVertical:'top'},error:{color:'#D33',fontSize:12,marginBottom:spacing.sm},actions:{flexDirection:'row',justifyContent:'flex-end',gap:spacing.sm,marginTop:spacing.sm},secondary:{paddingHorizontal:spacing.lg,paddingVertical:12},secondaryText:{color:colors.textSecondary,fontWeight:'700'},primary:{backgroundColor:colors.primary,borderRadius:radii.pill,paddingHorizontal:spacing.xl,paddingVertical:12,minWidth:110,alignItems:'center'},primaryText:{color:colors.white,fontWeight:'800'}});
